### ISSUE TITLE
Error during minimizing

### ISSUE THREAD

**Issue by Fulgi86** [Code-Artist/MSChartExtension#16]
I have attached the plot on a form and during a minimizing in the a cursor is present on the plot the application crash.
The error is the followng:

   at System.Windows.Forms.DataVisualization.Charting.Axis.PositionToValue(Double position, Boolean validateInput)
   at System.Windows.Forms.DataVisualization.Charting.Axis.PixelPositionToValue(Double position)
   at System.Windows.Forms.DataVisualization.Charting.MSChartExtension.CheckAndUpdateTextAnnotationLocation(Chart chart, TextAnnotation textAnn, Double xStart, Double yStart)
   at System.Windows.Forms.DataVisualization.Charting.MSChartExtension.UpdateCursorLabelPosition(Chart sender)
   at System.Windows.Forms.DataVisualization.Charting.MSChartExtension.ChartControl_Resized(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Fulgi86** [comment]
Sure... 
Fist the normal work situation:
![image](https://github.com/Code-Artist/MSChartExtension/assets/94001342/5cac832b-4e11-441e-9778-4eca44a5f517)
Then the error when i have minimazed it:
![image](https://github.com/Code-Artist/MSChartExtension/assets/94001342/b592af19-4d64-4812-a212-5f3477de3a1d)

**Comment by Code-Artist** [comment]
Issue fixed in Version 3.10.2
